baseURL = "https://fripig.github.io/article_log/"
languageCode = "zh-TW"
defaultContentLanguage = "zh-TW"
title = "這邊只是備份"
theme = "cupper-hugo-theme-custom"
googleAnalytics = ""

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "這邊主要目的是紀錄,並沒有做太多篩選的動作"
  homeMetaContent = "這邊主要目的是紀錄,並沒有做太多篩選的動作,想看篩選過的可以到,[twitter](https://twitter.com/fripig),不過也有些我的碎碎唸就是了"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2019"
  codePenUser = "fripig"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5